# Generated by Django 5.1.1 on 2024-09-08 15:34

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid5,
                        help_text="Unique ID for a given account and bank number, and source system.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.BigIntegerField()),
                ("bank", models.PositiveSmallIntegerField()),
                (
                    "source",
                    models.CharField(
                        help_text="The source system for this account.", max_length=3
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("number", "bank"),
                        name="unique_account_for_source",
                        violation_error_message="The account, bank, and source already exixts.",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PrivateKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid5,
                        help_text="Unique ID for this private key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "private_key",
                    models.CharField(
                        help_text="The private key for a given account number.",
                        max_length=1000,
                    ),
                ),
                (
                    "acct_uuid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="validation.account",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("private_key"),
                        name="private_key_unique",
                        violation_error_message="The private key already exixts.",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PublicKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid5,
                        help_text="Unique ID for this public key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "public_key",
                    models.CharField(
                        help_text="The public key for a given account number.",
                        max_length=1000,
                    ),
                ),
                (
                    "acct_uuid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="validation.account",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("public_key"),
                        name="public_key_unique",
                        violation_error_message="The public key already exixts.",
                    )
                ],
            },
        ),
    ]
