# Generated by Django 5.1.1 on 2024-09-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatekey",
            name="private_key",
            field=models.CharField(
                editable=False,
                help_text="The private key for a given account number.",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="publickey",
            name="public_key",
            field=models.CharField(
                editable=False,
                help_text="The public key for a given account number.",
                max_length=1000,
            ),
        ),
    ]
