# Generated by Django 5.1.1 on 2024-09-10 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0003_alter_account_id_alter_privatekey_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatekey",
            name="group_id",
            field=models.UUIDField(
                default=uuid.uuid4, help_text="This ID groups sets of keys."
            ),
        ),
        migrations.AddField(
            model_name="publickey",
            name="group_id",
            field=models.UUIDField(
                default=uuid.uuid4, help_text="This ID groups sets of keys."
            ),
        ),
    ]
