# Generated by Django 5.1.1 on 2024-09-10 19:23

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0004_privatekey_group_id_publickey_group_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique ID for this key group.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="validation.account",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="privatekey",
            name="group_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="validation.keygroup"
            ),
        ),
        migrations.AlterField(
            model_name="publickey",
            name="group_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="validation.keygroup"
            ),
        ),
    ]
