# Generated by Django 5.1.1 on 2024-09-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0008_keygroup_creation_dt_keygroup_doc_num_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keygroup",
            name="exhausted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="keygroup",
            name="exhausted_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
