# Generated by Django 5.1.1 on 2024-09-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0009_alter_keygroup_exhausted_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="keygroup",
            old_name="account",
            new_name="account_id",
        ),
    ]
