# Generated by Django 5.1.1 on 2024-09-13 14:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0011_remove_validationkey_pv_key_acct_doc_num_unique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationkey",
            name="status",
            field=models.CharField(
                choices=[("a", "Available"), ("s", "Spent")],
                default="a",
                help_text="The status of the validation key.",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="ValidationKeyHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique ID for this key validation history entry.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "validation_result",
                    models.CharField(
                        choices=[("s", "Success"), ("f", "Failure")],
                        help_text="The result of the key validation attempt.",
                        max_length=1,
                    ),
                ),
                ("entry_dt", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(max_length=100)),
                (
                    "key_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="validation.validationkey",
                    ),
                ),
            ],
        ),
    ]
