# Generated by Django 5.1.1 on 2024-09-13 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0012_validationkey_status_validationkeyhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationkey",
            name="account_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="validation_key_account",
                to="validation.account",
            ),
        ),
        migrations.AlterField(
            model_name="validationkey",
            name="group_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="validation_key_group",
                to="validation.keygroup",
            ),
        ),
    ]
