# Generated by Django 5.1.1 on 2024-09-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0013_alter_validationkey_account_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationkey",
            name="message",
            field=models.CharField(
                default="blank",
                editable=False,
                help_text="A random string of chars to use for key validation.",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="validationkey",
            name="signature",
            field=models.CharField(
                default="blank",
                editable=False,
                help_text="The signature for the message using the private key.",
                max_length=256,
            ),
            preserve_default=False,
        ),
    ]
