# Generated by Django 5.1.1 on 2024-09-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validation", "0024_alter_validationkey_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationkey",
            name="private_key",
            field=models.CharField(
                editable=False,
                help_text="The private key for a given account number.",
                max_length=3500,
            ),
        ),
    ]
